trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.12
  displayName: Change python version

# - script: |
#     pip install -r requirements.txt -r requirements.dev.txt
#   displayName: Execute pip install

- script: |
    py -3.12 -m venv .venv
    . .venv/Scripts/activate
    pip install -r requirements.txt -r requirements.dev.txt
    pytest tests -v --cov --cov-branch --cov-report=xml --cov-report=html --junitxml=test_result/test-result.xml
    ls -l ./test_result
    cat test_result/coverage.xml 
  displayName: Execute pytest with coverage

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: "**/test-result.xml"
    testRunTitle: $(Build.DefinitionName)_$(Build.BuildNumber)_$(Build.BuildId)
  displayName: Publish Test Results

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/test_result/coverage.xml'
  displayName: Publish coverage report
