trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.12
  displayName: Change python version

- script: |
    pip install -r requirements.txt -r requirements.dev.txt
  displayName: Execute pip install

- script: |
    pytest tests -v --cov --cov-branch --cov-report=xml --cov-report=html --junitxml=test_result/test-result.xml
  displayName: Execute pytest with coverage

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: "**/test-result.xml"
    testRunTitle: $(Build.DefinitionName)_$(Build.BuildNumber)_$(Build.BuildId)
  displayName: Publish Test Results

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  displayName: Publish coverage report
