trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.12
    architecture: 'x64'
    addToPath: true
  displayName: ‘Change python version’

- script: |
    pip install -r requirements.txt -r requirements.dev.txt
  displayName: ‘Execute pip install’

- script: |
    pytest tests -v --cov --cov-report=xml --cov-report=html
  displayName: “Execute pytest with coverage”

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: ‘$(System.DefaultWorkingDirectory)/**/coverage.xml’
    reportDirectory: ‘$(System.DefaultWorkingDirectory)/**/htmlcov’
  displayName: ‘Publish Cobertura Coverage Report’
