name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements.dev.txt

    - name: Run tests
      run: |
        pytest tests -v --cov --cov-branch --cov-report=xml --cov-report=html --junitxml=test_result/test-result.xml

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.11
      with:
        reports: 'test_result/coverage.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline_AzurePipelines;MarkdownSummaryGithub'
        verbosity: 'Info'
        tag: '${{ github.run_number }}_${{ github.run_id }}'
        toolpath: 'reportgeneratortool'

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport    
        path: coveragereport

    - name: Publish coverage in build summary
      run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
      shell: bash
